# Generated by Django 5.0 on 2025-07-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Propery',
            new_name='Property',
        ),
    ]
